### ISSUE TITLE
Support html anchors

### ISSUE THREAD

**Issue by tkruse** [wooorm/remark-validate-links#1]
Hi,

I beleve this only valdate simple header links, not html anchor links, right?
http://stackoverflow.com/questions/6695439/how-do-you-create-link-to-a-named-anchor-in-multimarkdown

Example:
```
./node_modules/.bin/mdast -u mdast-slug -u mdast-validate-links example.md
When commenting, please note [the introduction](#S-introduction)

# <a name="S-introduction"></a> In: Introduction

Text


example.md
  1:30-1:65  warning  Link to unknown heading: `S-introduction`

⚠ 1 warning
```

**Comment by wooorm** [comment]
Yup, it doesn’t. It supports github, npm, and other “heading” auto id’s.

**mdast** doesn’t parse HTML (markdown doesn’t care if HTML is in real, valid, &c.). HTML can be a mess: in fact, the point of mdast is to not only think about compiling to HTML, but also support other systems (e.g., man pages or react), which all simply discard HTML.

To add this, I recommend creating something that parses HTML nodes and adds the first found `name` attribute to `node.htmlAtributes.id` (that’s what `mdast-validate-links` looks for). In addition, there should be a tiny change [here](https://github.com/wooorm/mdast-validate-links/blob/407aa415d97afe30482d6ba9e5204b610a1494fc/index.js#L314), from `, 'heading'` to `''` to make validate-links work for non-headers too.

It’s not really on (the top of) my TODO list, but [`wooorm/hast`](https://github.com/wooorm/mdast) might be of interest if you’d like to integrate.

**Comment by tkruse** [comment]
Well, this is not about parsing html, but about parsing markdown the ```<a name="foo"></a>``` tags that can be found using regexes are really part of markdown I think, because markdown does not provide another way to define anchors without defining a header, as far as I know. So if validate-links could parse just these tags, that would be a great help to Markdown authors.

**Comment by wooorm** [comment]
I don’t think it’s **mdast-validate-links** which should parse HTML, just like I don’t think it’s **mdast-validate-links** job to detect slugs (that’s mdast-slug). That should be another module, which I’m currently not willing to write (sorry).

It is **mdast-validate-links**’s place to ensure other modules can interact with it, by exposing `node.data.id` or `node.data.htmlAtributes.id`; that’s why this issue is still open.

The fact that markdown doesn’t expose anchors means HTML anchors are no portable (and probably not safe) to other formats. This is part of why I’m not that interested in working on this.

Also, regarding “just parse these tags”, how about `<a name="foo">` (unclosed),  `<a name="foo"></a><a name="bar"></a>` (multiple), or thousands of HTML characters?

I can provide help if you’d be interested in building this though.

**Comment by tkruse** [comment]
I don't know what the word "slug" means, but maybe indeed I mean that mdast-slug should parse those tags in markdown. Indeed parsing the possible anchor variations can be horrible (so maybe regex is not a good approach).

I am not sure whether html anchors are generally not portable to other formats, this really depends on any given tools willingness to handle html anchors (I need to check pandoc anyway). If everbody uses them in their markdown, tools will follow.

**Comment by wooorm** [comment]
[Slug](https://en.wikipedia.org/wiki/Semantic_URL#Slug).

A more simple approach would be to only support a single HTML element, with content set to the empty string, with one attribute, namely `name`: E.g., `<span name="foo"></span>` or `<a name="base"></a>`.

But again, I’m not going to create it. I can help you with setting up a plugin/utility though!

**Comment by tkruse** [comment]
ok, wish I had the time, but have not. Closing as invalid.

**Comment by wooorm** [comment]
For now I’m reopening, just to reminded that this plugin should support non-headings, `htmlAttributes.name`, and I’ll add a section on possible future improvements where I describe this idea.

Thanks for the idea! :+1:

**Comment by igor-tsiglyar** [comment]
FYI markdownlint [supports](https://github.com/DavidAnson/markdownlint/blob/main/doc/md051.md) links to anchor. It won't validate links to other files, however, but there is a plugin for that that [recently](https://github.com/theoludwig/markdownlint-rule-relative-links/releases/tag/v2.2.0) has been updated to also support anchor links.
