### ISSUE TITLE
repository argument and package.json repository objects

### ISSUE THREAD

**Issue by davidtheclark** [wooorm/remark-validate-links#14]
> You can pass a repository, containing anything package.jsons repository can handle.

That confused me a bit, because it can't actually handle anything `package.json` can handle, right? I couldn't make it work with the stringified object that I get when `npm init` creates a `package.json`, e.g.

```
"repository": {
    "type": "git",
    "url": "git+https://github.com/mapbox/batfish.git"
 }
```

What do you think would be the most clear way to explain this in the docs? Unfortunately, it doesn't look like npm clearly documents the string values possible the `repository` field: https://docs.npmjs.com/files/package.json#repository

**Comment by wooorm** [comment]
Hmm, what that line means, is that any value the `repository` field in `package.json` files is supported. I thought that was true, or do you have a case where it isn’t?

**Comment by davidtheclark** [comment]
The value of the `repository` field can be an object, like the one in the snippet above. If I `JSON.stringify` that object, it does not work. If I provide just the `url` in that object, it doesn't work, either.

**Comment by wooorm** [comment]
Oh, yeah you can just pass in the object, so like `require('./package.json').repository` will work, but `JSON.stringify(...)` won't.

At least, it should; are you saying passing in `{repository: 'git+https://github.com/mapbox/batfish.git'}` doesn’t work?

**Comment by davidtheclark** [comment]
That doesn't work, no. Here are some examples of errors:

```
Error: Cannot parse `repository:"https://github.com/mapbox/batfish.git"` as JSON: Unexpected token h in JSON around position 16

Error: Cannot parse `repository:{repository: "git+https://github.com/mapbox/batfish.git" }` as JSON: Unexpected token h in JSON around position 35

Error: Cannot parse `repository:{"repository": "https://github.com/mapbox/batfish.git" }` as JSON: Unexpected token h in JSON around position 31

Error: Cannot parse `repository:{"repository": {
      "type": "git",
      "url": "git+https://github.com/mapbox/batfish.git"
    }}` as JSON: Unexpected token h in JSON around position 71

Error: Cannot parse `repository:"git+https://github.com/mapbox/batfish.git"` as JSON: Unexpected token h in JSON around position 20
```

**Comment by wooorm** [comment]
How weird! I’ve got two Qs:
1. is there a value you can successfully pass in?
2. How are you passing those values in?

**Comment by davidtheclark** [comment]
@wooorm: I suppose writing tests would be more helpful, huh ... maybe I can get to that today.

> is there a value you can successfully pass in?

Yeah, something like the README exemplifies: `mapbox/batfish`.

> How are you passing those values in?

I'm using `child_process.exec`, actually, and giving it `validate-links=repository:${repo}`, where `repo` is one of those values.

**Comment by wooorm** [comment]
I found the bug, and it’s a problem with the CLI. Hold on a sec while I try to figure out how to best deal with this!

**Comment by davidtheclark** [comment]
![thanks-pickle](https://user-images.githubusercontent.com/628431/27764389-29127236-5e4d-11e7-92f5-cad8385fc0b7.gif)

**Comment by wooorm** [comment]
Hah, first off: why does the dude wear half a traffic cone on his head? 😉
Most importantly: thank you for finding the bug! I mostly use config files, so didn't run into this before.

Anyway, it’s deployed now!
