### ISSUE TITLE
Validate external links

### ISSUE THREAD

**Issue by davidtheclark** [wooorm/remark-validate-links#15]
I'm sure you've considered the possibility of validating *external* links, as well as links to headings and docs. I couldn't find an explanation, though. Is this a feature you're interested in?

**Comment by wooorm** [comment]
Yeah, I’d love that. There’s [this lint rule](https://github.com/wemake-services/remark-lint-are-links-valid), but I think there are [some downsides](https://github.com/sindresorhus/awesome-lint/issues/19) to it.

Anyway, I’d say a different project. Maybe it could be set-up to as an agnostic link-checker wrapped for both remark and rehype?

**Comment by davidtheclark** [comment]
@wooorm: Here's a new plugin to try: https://github.com/davidtheclark/remark-lint-no-dead-links. https://github.com/tcort/link-check looks pretty robust, so I thought I'd try wrapping that. I'll be experimenting with this — let me know if you try it out and have any feedback!
