### ISSUE TITLE
Detecting links that are not links in GFM 

### ISSUE THREAD

**Issue by jayvdb** [wooorm/remark-validate-links#3]
Whereas the last build, from 2 months ago, was green, we only noticed a new error occurring

`1 ≤ k ≤ 55, S[k] = [100003 - 200003k + 300007k^3]   (modulo 1000000)` 

is being detected as a link to `modulo%201000000`.  GFM does not render it as a link.

See https://travis-ci.org/jayvdb/PocketEuler/builds/158191147

We have [a workaround](https://github.com/imsky/PocketEuler/pull/58), by using a LaTeX noop between the square and round brackets, but maybe you're interested in finding the problem.

**Comment by wooorm** [comment]
Hi! Sorry this went unanswered for so long. Could you create a new issue (I feel remark’s issue tracker is more suitable though) if this is still affecting you?

**Comment by jayvdb** [comment]
Still occurring.  Re-raised in the other repo as requested.
