### ISSUE TITLE
Validation features

### ISSUE THREAD

**Issue by urosjarc** [wooorm/remark-validate-links#4]
- [ ] log error if no link is present: `[No link provided...]()`
- [ ] log error if site don't exist: `[http call returns !2xx status](http://doNotExist.com)`

**Comment by wooorm** [comment]
Thanks @urosjarc for your first issue! I don’t think these features should be in this project, but in others.

The first is a very valid thing to have, but maybe it could be in [remark-lint](https://github.com/wooorm/remark-lint)? I opened an issue there.

And the second, as it requires an internet connection, and i’d like this project to work without as well.
Let me know if you’d want to build it, maybe I can help.

**Comment by urosjarc** [comment]
Well et least there should be some url reqex validation... I will provide with the code.

**Comment by urosjarc** [comment]
I will make some pull requeat, to show what i meant...
